version: "3.8"

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=/data/database.db
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - data:/data
    expose:
      - "5000"
    networks:
      - web
    restart: unless-stopped

  openresty:
    image: openresty/openresty:alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/lua:/etc/nginx/lua:ro
      - letsencrypt:/etc/letsencrypt
      - acme_challenges:/var/www/certbot
    networks:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - acme_challenges:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      'trap exit TERM; while :; do sleep 12h; certbot renew --webroot -w /var/www/certbot --agree-tos --non-interactive; done'
    networks:
      - web
    restart: unless-stopped

volumes:
  data:
  letsencrypt:
  acme_challenges:

networks:
  web:

